server:
  port: 8080

cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: youKey
      secret-key: youKey
    end-point:
      uri: yourQueue